FROM alpine as build-env
RUN apk add --no-cache build-base
WORKDIR /app
COPY main.c .
# Compile the binaries
RUN gcc -o server main.c

FROM alpine
COPY --from=build-env /app/server /app/server
WORKDIR /app
EXPOSE 61000/udp
CMD ["/app/server", "61000", "20"]
