SERVER_IP="127.0.0.1"
SERVER_PORT="61000"
PACKET_AMOUNT="500"
DELAY_MULTIPLIER="1000"

make
./client.out $SERVER_IP $SERVER_PORT $PACKET_AMOUNT $DELAY_MULTIPLIER

# docker run --rm -it --net=host client
