apiVersion: v1 
kind: Pod
metadata:
  name: udpclient
spec:
  restartPolicy: Never
  containers:
  - name: client
    image: ocebenzer/cmpe492-client:1
    resources:
      limits:
        cpu: "1000m"
        memory: "512Mi"
    command: ["/app/client"]
    args: ["$(SERVER_IP)", "$(SERVER_PORT)", "$(PACKET_AMOUNT)"]
    # ports:
    # - containerPort: 61000
    #   protocol: UDP
    env:
    - name: SERVER_IP
      value: "172.17.0.3"
    - name: SERVER_PORT
      value: "61000"
    - name: PACKET_AMOUNT
      value: "600"
