apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  restartPolicy: Never
  containers:
  - name: client
    image: ocebenzer/udpclient
    resources:
      limits:
        cpu: "1000m"
        memory: "512Mi"
    command: ["/app/client"]
    args: ["$(SERVER_IP)", "$(SERVER_PORT)", "$(PACKET_AMOUNT)"]
    env:
    - name: SERVER_IP
      value: "172.17.0.4"
    - name: SERVER_PORT
      value: "61000"
    - name: PACKET_AMOUNT
      value: "6000"
