apiVersion: v1
kind: Pod
metadata:
  name: server2
spec:
  restartPolicy: Never
  containers:
  - name: server
    image: ocebenzer/udpserver
    resources:
      limits:
        cpu: "1000m"
        memory: "512Mi"
    command: ["/app/server"]
    args: ["$(PORT)", "$(LOGFILE_PATH)"]
    env:
    - name: PORT
      value: "61000"
    - name: LOGFILE_PATH
      value: "/storage/server.csv"
    volumeMounts:
      - mountPath: "/storage"
        name: mymount
  volumes:
    - name: mymount
      persistentVolumeClaim:
        claimName: mypvc