FROM alpine as build-env
RUN apk add --no-cache build-base
WORKDIR /app
COPY server.c .
# Compile the binaries (-lm is to link math.c)
RUN gcc server.c -o server -lm

FROM alpine
COPY --from=build-env /app/server /app/server
EXPOSE 61000/udp
