apiVersion: v1
kind: Pod
metadata:
  name: bbu2
spec:
  nodeName: cloudran-m02
  restartPolicy: Never
  containers:
  - name: server
    image: ocebenzer/udpserver
    resources:
      limits:
        cpu: "800m"
        memory: "400M"
    command: ["/app/server"]
    args: ["$(PORT)", "$(LOGFILE_PATH)", "$(SERVER_ID)"]
    env:
    - name: PORT
      value: "61000"
    - name: LOGFILE_PATH
      value: "/nfs/bbu2.csv"
    - name: SERVER_ID
      value: "bbu2.1"
    volumeMounts:
      - name: nfs
        mountPath: /nfs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs