apiVersion: v1
kind: Pod
metadata:
  name: bbu3.2
spec:
  nodeName: k3d-bbu-node-0
  restartPolicy: Never
  containers:
  - name: server
    image: ocebenzer/udpserver
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
    command: ["/app/server"]
    args: ["$(PORT)", "$(LOGFILE_PATH)", "$(SERVER_ID)"]
    env:
    - name: PORT
      value: "61000"
    - name: LOGFILE_PATH
      value: "/storage/bbu1.csv"
    - name: SERVER_ID
      value: "BBU3.2"
    volumeMounts:
      - mountPath: "/storage"
        name: mymount
  volumes:
    - name: mymount
      persistentVolumeClaim:
        claimName: mypvc