apiVersion: v1
kind: Pod
metadata:
  name: bbu4
spec:
  nodeName: cloudran-m03
  restartPolicy: Never
  containers:
  - name: server
    image: ocebenzer/udpserver
    resources:
      limits:
        cpu: "500m"
        memory: "512M"
    command: ["/app/server"]
    args: ["$(PORT)", "$(LOGFILE_PATH)", "$(SERVER_ID)"]
    env:
    - name: PORT
      value: "61000"
    - name: LOGFILE_PATH
      value: "/nfs/bbu4.csv"
    - name: SERVER_ID
      value: "BBU4"
    volumeMounts:
      - name: nfs
        mountPath: /nfs
  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs