apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: nfs
  capacity:
    storage: 256M
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.244.1.2
    path: /
  claimRef:
    name: nfs
    namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256M