apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  nodeName: cloudran
  storageClassName: mystorage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi