apiVersion: v1
kind: Pod
metadata:
  name: rru2
spec:
  nodeName: cloudran
  restartPolicy: Never
  containers:
  - name: client
    image: ocebenzer/udpclient
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
    command: ["/app/client"]
    args: ["$(SERVER_IP)", "$(SERVER_PORT)", "$(PACKET_AMOUNT)", "$(DELAY_MULTIPLIER)"]
    env:
    - name: SERVER_IP
      value: "172.17.0.5"
    - name: SERVER_PORT
      value: "61002"
    - name: PACKET_AMOUNT
      value: "60000"
    - name: DELAY_MULTIPLIER
      value: "100000"
