apiVersion: v1
kind: Pod
metadata:
  name: rru3
spec:
  nodeName: minikube
  restartPolicy: Never
  containers:
  - name: client
    image: ocebenzer/udpclient
    resources:
      limits:
        cpu: "50m"
        memory: "64M"
    command: ["/app/client"]
    args: ["$(SERVER_IP)", "$(SERVER_PORT)", "$(PACKET_AMOUNT)", "$(DELAY_MULTIPLIER)"]
    env:
    - name: SERVER_IP
      value: "10.244.0.4"
    - name: SERVER_PORT
      value: "61003"
    - name: PACKET_AMOUNT
      value: "6000"
    - name: DELAY_MULTIPLIER
      value: "10000"
