apiVersion: v1
kind: Pod
metadata:
  name: rru4
spec:
  nodeName: cloudran
  restartPolicy: Never
  containers:
  - name: client
    image: ocebenzer/udpclient
    resources:
      limits:
        cpu: "125m"
        memory: "128M"
    command: ["/app/client"]
    args: ["$(SERVER_IP)", "$(SERVER_PORT)", "$(PACKET_AMOUNT)", "$(DELAY_MULTIPLIER)"]
    env:
    - name: SERVER_IP
      value: "10.244.2.10"
    - name: SERVER_PORT
      value: "61004"
    - name: PACKET_AMOUNT
      value: "600"
    - name: DELAY_MULTIPLIER
      value: "1000"
