apiVersion: v1 
kind: Pod
metadata:
  name: sdn
spec:
  nodeName: minikube
  restartPolicy: Never
  containers:
  - name: sdn
    image: ocebenzer/udpsdn
    resources:
      limits:
        cpu: "200m"
        memory: "128M"
    command: ["/app/sdn"]
    stdin: true
    tty: true